apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config-template
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  node-id: "0"
  server.properties: |
    # Basic Kafka settings
    num.network.threads=3
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    
    # Topic settings
    num.partitions=1
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    
    # Log settings
    log.dirs=/bitnami/kafka/data
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    
    # KRaft settings
    process.roles=${KAFKA_CFG_PROCESS_ROLES}
    node.id=${KAFKA_CFG_NODE_ID}
    controller.quorum.voters=${KAFKA_CONTROLLER_QUORUM_VOTERS}
    controller.listener.names=${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
    listeners=${KAFKA_CFG_LISTENERS}
    advertised.listeners=${KAFKA_CFG_ADVERTISED_LISTENERS}
    listener.security.protocol.map=${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
    inter.broker.listener.name=PLAINTEXT 