apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  ports:
  - name: kafka
    port: 9092
    targetPort: kafka
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  clusterIP: None
  ports:
  - name: kafka
    port: 9092
    targetPort: kafka
  - name: controller
    port: 9093
    targetPort: controller
  selector:
    app: kafka 