apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: {{ .Values.namespace }}
  labels:
    app: mailpit
spec:
  selector:
    app: mailpit
  ports:
    - port: {{ .Values.mailpit.smtpPort }}
      targetPort: smtp
      name: smtp
    - port: {{ .Values.mailpit.uiPort }}
      targetPort: ui
      name: ui
  type: ClusterIP
