apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceName | default "redis" }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: {{ .Values.redis.serviceName }}
    app.kubernetes.io/name: redis
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: {{ .Values.redis.port | default 6379 }}
    targetPort: redis
    protocol: TCP
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis-master
    app.kubernetes.io/name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.headlessServiceName | default "redis-headless" }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: {{ .Values.redis.serviceName }}
    app.kubernetes.io/name: redis
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: redis
    port: {{ .Values.redis.port | default 6379 }}
    targetPort: redis
    protocol: TCP
  {{- if .Values.redis.metrics.enabled }}
  - name: metrics
    port: 9121
    targetPort: metrics
    protocol: TCP
  {{- end }}
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: {{ .Values.redis.serviceName }}
    app.kubernetes.io/name: redis 