version: "3"

vars:
  NODE_ENV: development
  DATABASE_URL: "postgresql://username:password@localhost:5432/ledger"
  NODE_TLS_REJECT_UNAUTHORIZED: 0

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
    desc: Lists all available tasks

  dev:
    cmds:
      - bun run dev
    env:
      NODE_ENV: "{{.NODE_ENV}}"
      DATABASE_URL: "{{.DATABASE_URL}}"
    desc: Run the development server

  install:
    cmds:
      - bun install
    desc: Install project dependencies

  build:
    cmds:
      - bun run build
    env:
      NODE_ENV: production
      DATABASE_URL: "{{.DATABASE_URL}}"
    desc: Build the application for production

  start:
    cmds:
      - bun run start
    env:
      NODE_ENV: production
      DATABASE_URL: "{{.DATABASE_URL}}"
    desc: Start the production server

  lint:
    cmds:
      - bun run lint
    desc: Run ESLint to check code quality

  format:
    cmds:
      - bun run format
    desc: Format code using Prettier

  clean:
    cmds:
      - rm -rf node_modules
      - rm -rf .next
      - rm -rf dist
    desc: Clean build artifacts and dependencies

  db:generate:
    cmds:
      - bun run db:generate
    env:
      DATABASE_URL: "{{.DATABASE_URL}}"
    desc: Generate database migrations using Drizzle

  db:push:
    cmds:
      - bun run db:push
    env:
      DATABASE_URL: "{{.DATABASE_URL}}"
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    desc: Push schema changes to the database

  db:studio:
    cmds:
      - bun run db:studio
    env:
      DATABASE_URL: "{{.DATABASE_URL}}"
    desc: Open Drizzle Studio to manage database

  db:migrate:
    cmds:
      - bun run db:migrate
    env:
      DATABASE_URL: "{{.DATABASE_URL}}"
    desc: Run database migrations

  docker:build:
    desc: Build the Docker image with environment variables
    cmds:
      - docker build --build-arg NODE_ENV=production --build-arg DATABASE_URL="{{.DATABASE_URL}}" -t ledger-admin .

  docker:run:
    desc: Run the Docker container
    cmds:
      - docker run -p 3000:3000 --env-file .env ledger-admin

  docker:compose:
    desc: Start the database and application using docker-compose
    cmds:
      - docker-compose up -d

  gca:
    desc: git commit amend no edit
    cmds:
      - git add . && git commit --amend --no-edit

