version: "3"

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
    desc: Lists all available tasks

  dev:
    cmds:
      - bun dev
    desc: Run the development server

  install:
    cmds:
      - bun install
    desc: Install project dependencies

  build:
    cmds:
      - bun run build
    desc: Build the application for production

  start:
    cmds:
      - bun run start
    desc: Start the production server

  lint:
    cmds:
      - bun run lint
    desc: Run ESLint to check code quality

  format:
    cmds:
      - bun run format
    desc: Format code using Prettier

  clean:
    cmds:
      - rm -rf node_modules
      - rm -rf .next
      - rm -rf dist
      - rm bun.lock
    desc: Clean build artifacts and dependencies

  db:generate:
    cmds:
      - bun run db:generate
    desc: Generate database migrations using Drizzle

  db:push:
    cmds:
      - bun run db:push
    desc: Push schema changes to the database

  db:studio:
    cmds:
      - bun run db:studio
    desc: Open Drizzle Studio to manage database

  db:migrate:
    cmds:
      - bun run db:migrate
    desc: Run database migrations

  docker:build:
    desc: Build the Docker image with environment variables
    cmds:
      - docker build -t ledger-admin .

  docker:build:dev:
    desc: Build the Docker image with environment variables registry.gitlab.com/ipps-gtm/ledger-admin:dev
    cmds:
      - docker buildx build --platform linux/amd64 -t registry.gitlab.com/ipps-gtm/ledger-admin:dev --push .

  docker:run:
    desc: Run the Docker container
    cmds:
      - docker run -p 3000:3000 --env-file .env ledger-admin

  docker:compose:
    desc: Start the database and application using docker-compose
    cmds:
      - docker-compose up -d

  gca:
    desc: git commit amend no edit
    cmds:
      - git add . && git commit --amend --no-edit

  # k8s tasks
  set-ns:
    desc: Set k8s namespace (later change this ns to stc-ledger-dev)
    cmds:
      - kubectl config set-context --current --namespace=oneboss-dev

  helm:i:
    desc: Install the helm chart
    cmds:
      - helm install ledger-admin ./k8s/helm -n oneboss-dev

  helm:d:
    desc: Delete the helm chart
    cmds:
      - helm delete ledger-admin -n oneboss-dev

  helm:u:
    desc: Upgrade the helm chart
    cmds:
      - helm upgrade ledger-admin ./k8s/helm -n oneboss-dev

  fwd:pg:
    desc: Forward port 5432 to the database
    cmds:
      - kubectl port-forward svc/postgresql 5434:5432 -n oneboss-dev