apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: invgen-dev
  labels:
    app: kafka-client
spec:
  containers:
    - name: kafka-client
      image: confluentinc/cp-kafka:7.4.0
      command:
        - sh
        - -c
        - "exec tail -f /dev/null"
      env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka-headless:9092"
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
