namespace: invgen-dev
environment: development
ingressClass: public-nginx
api:
  serviceName: inv-api
  host: invoice-dev.treewalkr.dev
  servicePort: 80
  containerPort: 3000
  image:
    repository: registry.gitlab.com/ipps-gtm/invoice-generator-api:dev
    pullPolicy: Always
    pullSecretName: gitlab-registry-credentials
  cert:
    secretName: cloudflare-origin-cert
    certPath: certs/dev/cert.pem
    keyPath: certs/dev/key.pem
  secrets:
    databaseUrl: postgres://devuser:devpasswd@postgresql.invgen-dev.svc.cluster.local:5432/invoice_gen_dev?sslmode=disable
    jwtSecret: 89e2ced60fa637937aed1901f9e31cab565ce57e7ca34a06b0fe56be62b277a7
    encryptionKey: 9d65f4ca40d54839d8a0d12462a586bad1231fa8f5c4571cd3b104f0636d4da1
    encryptionSalt: ba8fd87d0fe354480aa0a83a230b6336
    rsaPrivateKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUUMzcmZBZ3lRUlNEWUlKOU12eVVFS0cwS084RDBhWnJCckZEdkRTNmZKRFZCTHlRUzJWCmJjSWoyKzJJZkNsNDZVOUxnZXBBd0creHRocDVlY3cyWkMvU0lUS1pYZCt5eVdxUENmQXpXVmZhSXd1OE5qcFcKRGt3bExxaFpxd1lkRXZoL1lWTDVXZ2VCWVFocExvRW8rVWVBMDNQakZwdldqTS9qQTlpeXlmUzVNd0lEQVFBQgpBb0dCQUpiSFhBVXR2alExRG5ocDBUazZsVUhoNTJhckM0TitlZ01sZnA5RW1EQ1l4V3pFQUUxWDZqUlJoeTJ3CjdzSm9rMFVpZ2s5aEtNOHk4NHlnWlBpSlNZN0o4ZW1rckh1Z05tUnhGWDZIbERTYll3N3dqWTBwNkNxVlJCbEkKYmplL3U0dHJIZkxnNE4vc0ppQTcwNVNKeXd3elBFOHlTZTBKUm94cXlpVGMzeGJSQWtFQTZPTzhDdDdzUDlZegovUS85a0NwYWYxSWZaSW1zU2xhMkRheGg4MVcxZUtzd0VGaGR6bU9UNXhoT1dkWEVPOVBLZGxndXhhSjA2SVdZClZSWkZ6eEYybFFKQkFNbm9GUDhTUDFwOUtNL21jaFM2K0JsbFZsWmlha0JEdUNNWUF3cFVDbUlXZzdiWDRUbkIKckpwZk5KV05tQUwxREs2cXpSaVBvWHgwSThvYjROL05acWNDUUcyc2FhNjQ0b3NCaGdRajFxWmd1N04vNmhhLwptdXA3UVVyWkpsdWd2bEF3VmZjc2xpaU96bVVqRmlyS041cHhGOFI1ckxVWDEzUjFEWkxzWlQycG5LMENRRzNjCmhuQTBNWnkvTlpIS1JwRFpHMTVXTWFCWGRKRDdTQnB3V2xjb1cyMzc2amQzUitueFpFV3JRQ1dRSWdLWjdBaXUKajJLcDVLaWZXVW9EMlZ4dG0wa0NRRWhzYll6NHhqeTN2TThnRWlacDhGZEFQdnl0dXNhZ0NsYlpYYjhVRnVmegpVOTczRStHZXIzVXR6NWk4RmQ5UVd4MmVpZEYyNitKSk9pMkYzanY5UUxVPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
    rsaPublicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDM3JmQWd5UVJTRFlJSjlNdnlVRUtHMEtPOApEMGFackJyRkR2RFM2ZkpEVkJMeVFTMlZiY0lqMisySWZDbDQ2VTlMZ2VwQXdHK3h0aHA1ZWN3MlpDL1NJVEtaClhkK3l5V3FQQ2ZBeldWZmFJd3U4TmpwV0Rrd2xMcWhacXdZZEV2aC9ZVkw1V2dlQllRaHBMb0VvK1VlQTAzUGoKRnB2V2pNL2pBOWl5eWZTNU13SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
    redisUrl: redis://:redispass@redis-master.invgen-dev.svc.cluster.local:6379
    smtpHost: mailpit.invgen-dev.svc.cluster.local
    smtpPort: "1025"
    smtpUsername: ""
    smtpPassword: ""
    smtpFrom: noreply@invoice-gen.test
    emailProvider: smtp
  configs:
    environment: development
    appPort: 3000
    timezone: Asia/Bangkok
    bunDebug: 1
    v2BaseUrl: https://v2-merchantapi-sndbx1.ipps.co.th
    appBaseUrl: https://invoice-dev.treewalkr.dev/api/
    callbackWhitelist: http://localhost:3000
    mailpitUI: https://mailpit.treewalkr.dev
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

mailpit:
  host: mailpit.treewalkr.dev
  smtpPort: 1025
  uiPort: 8025
  image:
    repository: axllent/mailpit
    tag: "v1.15"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"

redis:
  serviceName: redis-master
  headlessServiceName: redis-headless
  port: 6379
  replicaCount: 1

  image:
    repository: docker.io/bitnami/redis
    tag: "7.0.15"
    pullPolicy: IfNotPresent

  auth:
    enabled: true
    secretName: redis
    secretKey: redis-password
    password: redispass

  metrics:
    enabled: true
    image:
      repository: docker-prod-registry.cn-hangzhou.cr.aliyuncs.com/global/redis-exporter
      tag: "1.37.0-debian-10-r39"
      pullPolicy: IfNotPresent
    redisAlias: redis

  configMaps:
    configuration: redis-configuration
    health: redis-health
    scripts: redis-scripts

  persistence:
    size: 10Gi
    storageClass: cbs
    accessMode: ReadWriteOnce

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  config:
    maxmemory: "512mb"
    maxmemoryPolicy: "allkeys-lru"
    maxclients: "10000"
    timeout: "0"
    appendonly: "yes"
    appendfsync: "everysec"

  serviceAccountName: redis

  tolerations:
    - key: dedicated
      operator: Equal
      value: bigdata
      effect: NoSchedule
postgresql:
  replicaCount: 1
  image:
    repository: postgres
    tag: "17"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  postgresUser: devuser
  postgresPassword: devpasswd
  postgresDb: invoice_gen_dev
  persistence:
    size: 10Gi

kafka:
  replicaCount: 3
  image:
    repository: bitnami/kafka
    tag: "3.5.1"
    pullPolicy: IfNotPresent
  persistence:
    size: "50Gi"
    storageClass: "cbs"
    accessMode: "ReadWriteOnce"
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  clusterID: "vqb3wDN_S1GrVaFkpiwfNg"
  controllerQuorumVoters: "1@kafka-0.kafka-headless.invgen-dev.svc.cluster.local:9093,2@kafka-1.kafka-headless.invgen-dev.svc.cluster.local:9093,3@kafka-2.kafka-headless.invgen-dev.svc.cluster.local:9093"
  tolerations:
    - key: dedicated
      operator: Equal
      value: bigdata
      effect: NoSchedule
    - key: eks.tke.cloud.tencent.com/eklet
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
