apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.serviceName }}-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: "{{ .Values.environment }}"
  NODE_TLS_REJECT_UNAUTHORIZED: "{{ .Values.app.configs.nodeTlsRejectUnauthorized }}"
  APP_NAME: "{{ .Values.app.configs.appName }}"
  OTP_EXPIRY_MINUTES: "{{ .Values.app.configs.otpExpiryMinutes }}"
  RESET_AUTH_TOKEN_EXPIRY_MINUTES: "{{ .Values.app.configs.resetAuthTokenExpiryMinutes }}" 