apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.serviceName }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: "{{ .Values.app.secrets.databaseUrl }}"
  JWT_SECRET: "{{ .Values.app.secrets.jwtSecret }}"
  ENCRYPTION_KEY: "{{ .Values.app.secrets.encryptionKey }}"
  SENDGRID_API_KEY: "{{ .Values.app.secrets.sendgridApiKey }}"
  SENDER_EMAIL_ADDRESS: "{{ .Values.app.secrets.smtpFrom }}" 