apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.serviceName }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_DSN: "{{ .Values.app.secrets.databaseUrl }}"
  JWT_SECRET: "{{ .Values.app.secrets.jwtSecret }}"
  ENCRYPTION_KEY: "{{ .Values.app.secrets.encryptionKey }}"
  ENCRYPTION_SALT: "{{ .Values.app.secrets.encryptionSalt }}"
  RSA_PRIVATE_KEY: "{{ .Values.app.secrets.rsaPrivateKey }}"
  RSA_PUBLIC_KEY: "{{ .Values.app.secrets.rsaPublicKey }}"
  REDIS_URL: "{{ .Values.app.secrets.redisUrl }}"
  SMTP_HOST: "{{ .Values.app.secrets.smtpHost }}"
  SMTP_PORT: "{{ .Values.app.secrets.smtpPort }}"
  SMTP_USERNAME: "{{ .Values.app.secrets.smtpUsername }}"
  SMTP_PASSWORD: "{{ .Values.app.secrets.smtpPassword }}"
  SMTP_FROM: "{{ .Values.app.secrets.smtpFrom }}" 