apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailpit
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.ingressClass }}
  tls:
    - hosts:
        - {{ .Values.mailpit.host }}
      secretName: {{ .Values.app.cert.secretName }}
  rules:
    - host: {{ .Values.mailpit.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mailpit
                port:
                  name: ui
