apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: postgresql
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  postgres-user: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  postgres-db: {{ .Values.postgresql.postgresDb | b64enc | quote }} 