apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.redis.serviceAccountName | default "redis" }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: {{ .Values.redis.serviceName }}
    app.kubernetes.io/name: redis
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }} 