apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.cert.secretName }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.app.cert.certPath | b64enc }}
  tls.key: {{ .Files.Get .Values.app.cert.keyPath | b64enc }}
